AllCops:
  Exclude:
    - bin/*
    - db/**/*.rb
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - test/*
    - config/puma.rb
    - Rakefile
    - config/environments/*
    - config/application.rb
    - config/initializers/*
    - config/spring.rb